language: java
jdk:
  - oraclejdk8
script: javac @java_files.txt && ./CreateMarsJar.sh
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    skip_cleanup: true
    overwrite: true
    file: "./Mars.jar"
    tag_name: "$TRAVIS_TAG"
    on:
      branch: master
      tags: true
